// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "sccpctrl1.h"

/////////////////////////////////////////////////////////////////////////////
// CSccpctrl1

IMPLEMENT_DYNCREATE(CSccpctrl1, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CSccpctrl1 properties

/////////////////////////////////////////////////////////////////////////////
// CSccpctrl1 operations
