// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "tohvshowctrl1.h"

/////////////////////////////////////////////////////////////////////////////
// CTohvshowctrl1

IMPLEMENT_DYNCREATE(CTohvshowctrl1, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CTohvshowctrl1 properties

/////////////////////////////////////////////////////////////////////////////
// CTohvshowctrl1 operations
